//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatBot.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на субъект:кто это_кто_кого_чей
        ///описание:объясни_расскажи_скажи_напиши_чего_что это_зачем это_почему это_что этот_зачем этот_почему этот_что эта_зачем эта_почему эта_это зачем_это почему_это что
        ///время:когда_во сколько_какие тайминги_тайминг_время
        ///причина:почему_зачем_отчего_в чем смысл_для чего_прикол
        ///место:где_куда_откуда_откуд_место_месте_в каком_в какой_локация_локации
        ///утверждение:ведь_но_или нет_не так_ли.
        /// </summary>
        internal static string Вопросы {
            get {
                return ResourceManager.GetString("Вопросы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на slardar:слардар_slardar_селедка_селёдка_guardian_слардара_селедку_селедке_слардаре_слардара_слардару_сельдь_сом
        ///slithereen:слизерин_слидерин_нага_сирена_slithereen_слардары_глубоководные_deep ones
        ///dark reef:темный риф_тёмный риф_риф_сларк_slark_сралк
        ///tidehunter:тайд_тайд хантер_тайдуха_tide_tide hunter_tidehunter
        ///dota:дота_дота 2_dota 2_dota_защита древних
        ///io:wisp_io_ио_висп.
        /// </summary>
        internal static string Имена_собственные {
            get {
                return ResourceManager.GetString("Имена_собственные", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на стратегия:стратегия_страта_идея_смысл игры_как играть_страте_идее
        ///лайн:линия_лайнинг_лейн_lane_line_ерли гейм_early game_начальный закуп_закупу
        ///файт:файт_fight_драка_битва_битве_драке_файте_файту
        ///предметы:айтемы_предметы_собирать_крафтить_покупать_брать_шмот_шмотки
        ///лор:история_лор_lore_биография_биографию_историю
        ///таланты:таланты_талант_20_25.
        /// </summary>
        internal static string Ключевые_слова {
            get {
                return ResourceManager.GetString("Ключевые_слова", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Это вопрос?
        ///Че?
        ///На что отвечать?
        ///Будь готов к непредвиденным последствиям
        ///Ты чего какой подозрительный, шпион что ли!?
        ///Извини, я не понял тебя
        ///Я не понял, что ты написал, возможно что-то гениальное
        ///Признайся, ты работаешь на Slark!.
        /// </summary>
        internal static string Непонятно {
            get {
                return ResourceManager.GetString("Непонятно", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на slardar:субъект:Слардар из рода змееногих, один из обитателей глубин, охраняет обширную сеть затонувших городов и скрытых ими древних ценностей._Слардар стоит на страже потайных сокровищниц, скрытых в бессветной пучине, и неусыпно охраняет их от подводных воров, посланных на морское дно алчными магами с поверхности. Страж верен своей службе как никто, а за его молчаливостью скрыто знание всех тайных морских проходов. Несмотря на жгучий свет, он поднимается на мелководье, чтобы разведать, не сговаривается ли [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Ответы_Имена_собственные {
            get {
                return ResourceManager.GetString("Ответы_Имена_собственные", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на стратегия:стратегия_страта_идея_смысл игры_как играть_страте_идее
        ///лайн:линия_лайнинг_лейн_lane_line_ерли гейм_early game_начальный закуп_закупу
        ///файт:файт_fight_драка_битва_битве_драке_файте_файту
        ///предметы:айтемы_предметы_собирать_крафтить_покупать_брать_шмот_шмотки
        ///лор:история_лор_lore_биография_биографию_историю
        ///таланты:таланты_талант_20_25.
        /// </summary>
        internal static string Ответы_Ключевые_слова {
            get {
                return ResourceManager.GetString("Ответы_Ключевые_слова", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на blink dagger:субъект:(2250) Легендарный кинжал, которым когда-то пользовался самый быстрый убийца на свете.
        ///blink dagger:описание:Blink Dagger обычно нужен героям, которым нехватает мобильности или инициаторам
        ///blink dagger:время:К 20 минуте
        ///blink dagger:причина:Для быстрого &quot;пик-оффа&quot; коров противника
        ///blink dagger:место:В основной лавке, в разделе Разное
        ///blink dagger:утверждение:Да_Нет
        ///power treads:субъект:(1400) Пара сапог, выделанных из жесткой кожи, которая способна изменять свои свойства по желани [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Ответы_Предметы {
            get {
                return ResourceManager.GetString("Ответы_Предметы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на спринт:спринт_sprint_guardian sprint_первый спелл_1 спелл_1 скилл_первый скилл
        ///стан:стан_краш_slithereen_второй спелл_2 спелл_2 скилл_второй скилл
        ///баш:пассивка_баш_bash_bash of the deep_третий спелл_3 спелл_3 скилл_третий скилл
        ///ульт:ульт_ульта_ультимейт_corrosive haze_минус броня_армор редакшн_armor reduction.
        /// </summary>
        internal static string Ответы_Способности {
            get {
                return ResourceManager.GetString("Ответы_Способности", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на blink dagger:blink_blink dagger_dagger_блинк_дагер_даггер_блинк дагер
        ///power treads:пт_pt_треды_treads_повер тредс_power treads
        ///phase boots:фазы_фейзы_phase_phase boots_синие ботинки
        ///boots of speed:сапог_сапоги_boots_boots of speed_ботинок_ботинки
        ///tranquil boots:транквилы_tranquil_зеленые ботинки
        ///hand of midas:мидас_midas_рука мидаса_hand of midas
        ///aghanim&apos;s scepter:аганим_аганим скипетр_скипетр аганима_aghanim_agh_aghs_agh&apos;s_aghanim&apos;s_aghanim scepter_aghanim&apos;s scepter
        ///aghanim&apos;s shard:aghanim&apos;s shard_s [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Предметы {
            get {
                return ResourceManager.GetString("Предметы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пиши по-человечески
        ///Кожанный мешок с костями, пиши разборчиво!
        ///Че тебе надо?
        ///Хочешь 3 рандомных факта? \n\t1)Хол нотна\n\t2)Слардар - лучший герой в Dota 2\n\t3)То что ты написал - кринж
        ///Ты че несешь?!
        ///КРИНЖАНУЛ
        ///Я даже не буду на это отвечать
        ///Я не буду на это отвечать
        ///Я не хочу на это отвечать, кожанный мешок с костями.
        /// </summary>
        internal static string Сарказм {
            get {
                return ResourceManager.GetString("Сарказм", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на спринт:спринт_sprint_guardian sprint_первый спелл_1 спелл_1 скилл_первый скилл
        ///стан:стан_краш_slithereen_второй спелл_2 спелл_2 скилл_второй скилл
        ///баш:пассивка_баш_bash_bash of the deep_третий спелл_3 спелл_3 скилл_третий скилл
        ///ульт:ульт_ульта_ультимейт_corrosive haze_минус броня_армор редакшн_armor reduction.
        /// </summary>
        internal static string Способности {
            get {
                return ResourceManager.GetString("Способности", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невероятно!
        ///Да ты что!?
        ///Прикольно, не знал
        ///ok.
        ///Допустим
        ///И что дальше?
        ///Ну ок
        ///Серьезно?
        ///Ага, а ещё ты хочешь сказать, что Slardar - не лучший герой в доте
        ///Ещё что скажешь?
        ///Думаешь, ты такой умный?
        ///Невероятно! (сейчас без сарказма).
        /// </summary>
        internal static string Утверждения {
            get {
                return ResourceManager.GetString("Утверждения", resourceCulture);
            }
        }
    }
}
